import json
from google import genai
from google.genai import types

class Paladin:
    def __init__(self, api_key, model_id):
        self.client = genai.Client(api_key=api_key)
        self.model_id = model_id.replace("models/", "")

    def generate_remediation(self, result_dict, endpoint, payload, loot=None):
        """
        Generates a professional vulnerability report using Gemini.
        """
        hypothesis = result_dict.get('hypothesis', 'Generic Vulnerability')
        status = result_dict.get('status_code', 0)
        finding_type = result_dict.get('finding_type', 'Unknown')
        response_body = result_dict.get('body', '')[:1500]
        loot_evidence = json.dumps(loot) if loot else "No secondary data harvested."

        critical_types = [
            "CRITICAL_LEAK", "INJECTION_PROOF", "AUTH_BYPASS", "DATA_EXFIL",
            "UNEXPECTED_DATA_LEAK", "PRIVILEGE_ESCALATION", "SENSITIVE_DATA_EXPOSURE"
        ]
        severity = "CRITICAL" if finding_type in critical_types else "HIGH"
        if status >= 500: severity = "MEDIUM/HIGH (Service Instability)"
        if status == 403: severity = "LOW/MEDIUM (Access Restriction)"
        if status == 404: severity = "LOW (Resource Not Found)"
        if status == 401: severity = "LOW/MEDIUM (Authentication Required)"

        prompt = f"""
        ACT AS A SENIOR SECURITY AUDITOR & PENETRATION TESTER. 
        
        STRIKE DATA:
        - Target Endpoint: {endpoint}
        - Vulnerability Hypothesis: {hypothesis}
        - Detected Category: {finding_type}
        - HTTP Status Code: {status}
        - Evidence Snippet: {response_body}
        - HARVESTED DATA (LOOT): {loot_evidence}

        TASK: Generate a professional vulnerability report based on this automated strike.
        
        MARKDOWN STRUCTURE:
        # 🛡️ BEHEMOTH FINDING: {hypothesis}
        
        ## 1. Executive Summary
        [Explain the business impact. Does this allow data theft, account takeover, or server shutdown? Specifically mention if the HARVESTED DATA proves a breach of PII (Personally Identifiable Information) or sensitive system IDs.]

        ## 2. Technical Breakdown
        * **Endpoint:** `{endpoint}`
        * **Method:** [Extracted from context]
        * **Payload:** `{json.dumps(payload)}`
        * **Severity:** {severity}
        * **HTTP Response:** {status}

        ## 3. Path to Exploitation
        [Detail how the payload bypassed the input validation or logic gates. If HARVESTED DATA is present, explain how the payload interacted with the backend to extract that specific data.]

        ## 4. Remediation (The 'Cure')
        ### 🛠️ Immediate Patch
        [Specific code-level fix, e.g., 'Use Parameterized Queries' or 'Implement Strict Type Checking']
        ### 🏛️ Strategic Hardening
        [Architectural advice, e.g., 'Implement a Zero-Trust Authorization Layer']

        ---
        *Generated by Behemoth Autonomous Security Engine*
        """

        is_thinking = "thinking" in self.model_id.lower()
        config_args = {"response_mime_type": "text/plain"}

        try:
            if is_thinking:
                config_args["thinking_config"] = types.ThinkingConfig(thinking_level="MEDIUM", include_thoughts=True)

            else:
                config_args = types.GenerateContentConfig(
                    response_mime_type="text/plain",
                    safety_settings=[
                        {"category": "HARM_CATEGORY_DANGEROUS_CONTENT", "threshold": "BLOCK_NONE"},
                        {"category": "HARM_CATEGORY_HARASSMENT", "threshold": "BLOCK_NONE"},
                        {"category": "HARM_CATEGORY_HATE_SPEECH", "threshold": "BLOCK_NONE"},
                        {"category": "HARM_CATEGORY_SEXUALLY_EXPLICIT", "threshold": "BLOCK_NONE"}
                    ]
                )
        
            response = self.client.models.generate_content(
                model=self.model_id,
                contents=prompt,
                config=config_args
            )
            
            if not response.text:
                return "🛡️ PALADIN NOTICE: Report generation blocked by safety filters. The evidence captured was too sensitive for the standard scribe."
                
            return response.text
        except Exception as e:
            return f"🛡️ PALADIN ERROR: Failed to scribe the report. {str(e)}"